### ISSUE TITLE
[]

### ISSUE THREAD

**Issue by PAMinerva** [CleftObsidian/WIP.PBD#6]

**Comment by CleftObsidian** [comment]
We apologize for the delay in responding.
This project will be extended to simulate all convex 3D objects.
For position-based dynamics, you might want to look at papers like “Detailed Rigid Body Simulation with Extended Position Based Dynamics” (2020).
I haven't finished the project yet, but I've also added a license.
Thanks for enjoying it!

**Comment by PAMinerva** [comment]
Thank you for the reply. 
Sorry for deleting the message, but I thought it was an abandoned project. 
It's fantastic news that you want to continue developing this project because it's easier for me to learn by reading your code—it's clear, straightforward (without the monstrosities of modern C++), and uses d3d12, which is the graphics API I know best.
I can't wait to keep reading and studying the new updates to this project. Currently, I'm watching the ten-minute physics series on YouTube, and then I'll dive into the paper you recommended. 
Oh, thanks for including the project's licensing info.
